const players = [
  // ATL
  { id: 70, name: "Rhyne Howard", team: "ATL", position: "G-F", number: "10", age: 24, height: "6'2\"", conf: "East", previousTeams: [] },
  { id: 120, name: "Naz Hillmon", team: "ATL", position: "F", number: "00", age: 25, height: "6'2\"", conf: "East", previousTeams: [] },
  { id: 121, name: "Te-Hina Paopao", team: "ATL", position: "G", number: "2", age: 23, height: "5'9\"", conf: "East", previousTeams: [] },
  { id: 122, name: "Jordin Canada", team: "ATL", position: "G", number: "21", age: 30, height: "5'6\"", conf: "East", previousTeams: ["SEA", "LAS"] },
  { id: 123, name: "Taylor Thierry", team: "ATL", position: "G-F", number: "5", age: 22, height: "6'1\"", conf: "East", previousTeams: [] },
  { id: 124, name: "Nia Coffey", team: "ATL", position: "F", number: "12", age: 30, height: "6'1\"", conf: "East", previousTeams: ["LVA", "PHO", "LAS"] },
  { id: 125, name: "Allisha Gray", team: "ATL", position: "G", number: "15", age: 30, height: "6'0\"", conf: "East", previousTeams: ["DAL"] },
  { id: 126, name: "Brionna Jones", team: "ATL", position: "F", number: "42", age: 30, height: "6'3\"", conf: "East", previousTeams: ["CON"] },
  { id: 127, name: "Shatori Walker-Kimbrough", team: "ATL", position: "G", number: "32", age: 30, height: "5'9\"", conf: "East", previousTeams: ["WAS", "PHO", "CON"] },
  { id: 128, name: "Maya Caldwell", team: "ATL", position: "G", number: "33", age: 27, height: "5'11\"", conf: "East", previousTeams: ["IND"] },
  { id: 129, name: "Brittney Griner", team: "ATL", position: "C", number: "42", age: 35, height: "6'9\"", conf: "East", previousTeams: ["PHO"] },

  // CHI
  { id: 9, name: "Angel Reese", team: "CHI", position: "F", number: "5", age: 21, height: "6'3\"", conf: "East", previousTeams: [] },
  { id: 10, name: "Ariel Atkins", team: "CHI", position: "G", number: "7", age: 28, height: "5'11\"", conf: "East", previousTeams: ["WAS"] },
  { id: 31, name: "Elizabeth Williams", team: "CHI", position: "F", number: "1", age: 31, height: "6'3\"", conf: "East", previousTeams: ["ATL"] },
  { id: 35, name: "Hailey Van Lith", team: "CHI", position: "G", number: "2", age: 23, height: "5'9\"", conf: "East", previousTeams: [] },
  { id: 7, name: "Sevgi Uzun", team: "CHI", position: "G", number: "0", age: 28, height: "5'10\"", conf: "East", previousTeams: ["DAL", "PHX"] },
  { id: 44, name: "Kamilla Cardoso", team: "CHI", position: "C", number: "10", age: 23, height: "6'7\"", conf: "East", previousTeams: [] },
  { id: 51, name: "Kia Nurse", team: "CHI", position: "G", number: "10", age: 29, height: "6'0\"", conf: "East", previousTeams: ["NYL", "PHX"] },
  { id: 54, name: "Maddy Westbeld", team: "CHI", position: "F", number: "21", age: 22, height: "6'3\"", conf: "East", previousTeams: [] },
  { id: 57, name: "Michaela Onyenwere", team: "CHI", position: "F", number: "12", age: 26, height: "6'0\"", conf: "East", previousTeams: ["NYL", "PHX"] },
  { id: 58, name: "Moriah Jefferson", team: "CHI", position: "G", number: "4", age: 30, height: "5'6\"", conf: "East", previousTeams: ["LVA", "DAL", "MIN", "PHX"] },
  { id: 67, name: "Rachel Banham", team: "CHI", position: "G", number: "24", age: 31, height: "5'9\"", conf: "East", previousTeams: ["MIN", "CON"] },
  { id: 68, name: "Rebecca Allen", team: "CHI", position: "G", number: "11", age: 32, height: "6'2\"", conf: "East", previousTeams: ["NYL", "CON"] },

  // CON
  { id: 96, name: "Marina Mabrey", team: "CON", position: "G", number: "5", age: 29, height: "5'11\"", conf: "East", previousTeams: ["LAS", "DAL", "CHI"] },
  { id: 84, name: "Aaliyah Edwards", team: "CON", position: "F", number: "24", age: 22, height: "6'3\"", conf: "East", previousTeams: ["WAS"] },
  { id: 98, name: "Haley Peters", team: "CON", position: "F-G", number: "7", age: 33, height: "6'3\"", conf: "East", previousTeams: ["LVA", "WAS", "ATL"] },
  { id: 99, name: "Olivia Nelson-Ododa", team: "CON", position: "C", number: "10", age: 25, height: "6'5\"", conf: "East", previousTeams: ["LAS"] },
  { id: 100, name: "Rayah Marshall", team: "CON", position: "C-F", number: "13", age: 21, height: "6'4\"", conf: "East", previousTeams: [] },
  { id: 101, name: "Bria Hartley", team: "CON", position: "G", number: "8", age: 33, height: "5'9\"", conf: "East", previousTeams: ["WAS", "NYL", "PHO", "IND"] },
  { id: 102, name: "Lindsay Allen", team: "CON", position: "G", number: "12", age: 30, height: "5'8\"", conf: "East", previousTeams: ["NYL", "LVA", "IND", "MIN", "CHI"] },
  { id: 103, name: "Robyn Parks", team: "CON", position: "F", number: "21", age: 33, height: "6'0\"", conf: "East", previousTeams: ["CHI"] },
  { id: 104, name: "Saniya Rivers", team: "CON", position: "G", number: "22", age: 22, height: "6'1\"", conf: "East", previousTeams: [] },
  { id: 105, name: "Kariata Diaby", team: "CON", position: "C", number: "23", age: 30, height: "6'4\"", conf: "East", previousTeams: [] },
  { id: 106, name: "Aneesah Morrow", team: "CON", position: "F", number: "24", age: 22, height: "6'1\"", conf: "East", previousTeams: [] },
  { id: 107, name: "Tina Charles", team: "CON", position: "C", number: "31", age: 37, height: "6'4\"", conf: "East", previousTeams: ["NYL", "WAS", "PHO", "SEA", "ATL"] },
  { id: 108, name: "Leila Lacan", team: "CON", position: "G", number: "47", age: 21, height: "5'11\"", conf: "East", previousTeams: [] },

  // DAL
  { id: 11, name: "Arike Ogunbowale", team: "DAL", position: "G", number: "24", age: 28, height: "5'8\"", conf: "West", previousTeams: [] },
  { id: 27, name: "DiJonai Carrington", team: "MIN", position: "G-F", number: "21", age: 27, height: "5'11\"", conf: "West", previousTeams: ["CON", "DAL"] },
  { id: 65, name: "Paige Bueckers", team: "DAL", position: "G", number: "5", age: 23, height: "6'0\"", conf: "West", previousTeams: [] },
  { id: 130, name: "NaLyssa Smith", team: "LVA", position: "F", number: "3", age: 25, height: "6'4\"", conf: "West", previousTeams: ["IND", "DAL"] },
  { id: 131, name: "Myisha Hines-Allen", team: "DAL", position: "F", number: "2", age: 30, height: "6'1\"", conf: "West", previousTeams: ["WAS", "MIN"] },
  { id: 132, name: "Kaila Charles", team: "DAL", position: "G-F", number: "3", age: 27, height: "6'1\"", conf: "West", previousTeams: ["CON", "ATL", "SEA"] },
  { id: 134, name: "Aziaha James", team: "DAL", position: "G", number: "10", age: 23, height: "5'8\"", conf: "West", previousTeams: [] },
  { id: 135, name: "JJ Quinerly", team: "DAL", position: "G", number: "11", age: 23, height: "5'8\"", conf: "West", previousTeams: [] },
  { id: 136, name: "Teaira McCowan", team: "DAL", position: "C", number: "15", age: 29, height: "6'7\"", conf: "West", previousTeams: ["IND"] },
  { id: 137, name: "Luisa Geiselsöder", team: "DAL", position: "C", number: "18", age: 25, height: "6'4\"", conf: "West", previousTeams: [] },
  { id: 138, name: "Maddy Siegrist", team: "DAL", position: "F", number: "20", age: 25, height: "6'2\"", conf: "West", previousTeams: [] },
  { id: 139, name: "Arike Ogunbowale", team: "DAL", position: "G", number: "24", age: 28, height: "5'8\"", conf: "West", previousTeams: [] },
  { id: 140, name: "Tyasha Harris", team: "DAL", position: "G", number: "52", age: 27, height: "5'10\"", conf: "West", previousTeams: ["CON"] },

  // GSV
  { id: 79, name: "Tiffany Hayes", team: "GSV", position: "G", number: "15", age: 36, height: "5'10\"", conf: "West", previousTeams: ["ATL", "CON", "LVA"] },
  { id: 109, name: "Kayla Thornton", team: "GSV", position: "F", number: "5", age: 33, height: "6'1\"", conf: "West", previousTeams: ["WAS", "DAL", "NYL"] },
  { id: 110, name: "Stephanie Talbot", team: "GSV", position: "F", number: "8", age: 31, height: "6'2\"", conf: "West", previousTeams: ["PHO", "MIN", "SEA", "LAS"] },
  { id: 111, name: "Janelle Salaun", team: "GSV", position: "F", number: "13", age: 0, height: "", conf: "West", previousTeams: [] },
  { id: 112, name: "Temi Fagbenle", team: "GSV", position: "C", number: "14", age: 0, height: "", conf: "West", previousTeams: [] },
  { id: 113, name: "Tiffany Hayes", team: "GSV", position: "G", number: "15", age: 36, height: "5'10\"", conf: "West", previousTeams: ["ATL", "CON", "LVA"] },
  { id: 114, name: "Kate Martin", team: "GSV", position: "G", number: "20", age: 25, height: "6'0\"", conf: "West", previousTeams: ["LVA"] },
  { id: 115, name: "Veronica Burton", team: "GSV", position: "G", number: "12", age: 25, height: "5'9\"", conf: "West", previousTeams: ["DAL", "CON"] },
  { id: 116, name: "Cecilia Zandalasini", team: "GSV", position: "F", number: "9", age: 29, height: "6'2\"", conf: "West", previousTeams: ["MIN"] },
  { id: 117, name: "Monique Billings", team: "GSV", position: "F", number: "25", age: 29, height: "6'4\"", conf: "West", previousTeams: ["ATL", "DAL", "PHO"] },
  { id: 118, name: "Kyara Linskens", team: "GSV", position: "C", number: "31", age: 29, height: "6'4\"", conf: "West", previousTeams: [] },
  { id: 119, name: "Julie Vanloo", team: "LAS", position: "G", number: "35", age: 32, height: "5'8\"", conf: "West", previousTeams: ["WAS", "GSV"] },

  // IND
  { id: 6, name: "Aliyah Boston", team: "IND", position: "F-C", number: "7", age: 24, height: "6'5\"", conf: "East", previousTeams: [] },
  { id: 14, name: "Brianna Turner", team: "IND", position: "F-C", number: "21", age: 29, height: "6'3\"", conf: "East", previousTeams: ["PHX", "CHI"] },
  { id: 16, name: "Caitlin Clark", team: "IND", position: "G", number: "22", age: 23, height: "6'0\"", conf: "East", previousTeams: [] },
  { id: 24, name: "Damiris Dantas", team: "IND", position: "C-F", number: "34", age: 33, height: "6'3\"", conf: "East", previousTeams: ["MIN", "ATL"] },
  { id: 38, name: "Jaelyn Brown", team: "IND", position: "G", number: "18", age: 26, height: "6'1\"", conf: "East", previousTeams: [] },
  { id: 46, name: "Kelsey Mitchell", team: "IND", position: "G", number: "0", age: 30, height: "5'8\"", conf: "East", previousTeams: [] },
  { id: 8, name: "Makayla Timpson", team: "IND", position: "F-C", number: "21", age: 23, height: "6'2\"", conf: "East", previousTeams: [] },
  { id: 53, name: "Lexie Hull", team: "IND", position: "G", number: "10", age: 26, height: "6'1\"", conf: "East", previousTeams: [] },
  { id: 60, name: "Natasha Howard", team: "IND", position: "F", number: "33", age: 34, height: "6'2\"", conf: "East", previousTeams: ["MIN", "SEA", "NYL", "DAL"] },
  { id: 77, name: "Sophie Cunningham", team: "IND", position: "G", number: "9", age: 29, height: "6'1\"", conf: "East", previousTeams: ["PHO"] },
  { id: 78, name: "Sydney Colson", team: "IND", position: "G", number: "51", age: 36, height: "5'8\"", conf: "East", previousTeams: ["NYL", "LVA", "MIN", "CHI"] },

  // LAS
  { id: 3, name: "Aari McDonald", team: "LAS", position: "G", number: "15", age: 26, height: "5'6\"", conf: "West", previousTeams: [] },
  { id: 12, name: "Azura Stevens", team: "LAS", position: "F-C", number: "23", age: 29, height: "6'6\"", conf: "West", previousTeams: ["CHI", "DAL"] },
  { id: 17, name: "Cameron Brink", team: "LAS", position: "F", number: "22", age: 23, height: "6'4\"", conf: "West", previousTeams: [] },
  { id: 25, name: "Dearica Hamby", team: "LAS", position: "F", number: "5", age: 31, height: "6'3\"", conf: "West", previousTeams: ["LVA"] },
  { id: 32, name: "Emma Cannon", team: "LAS", position: "F", number: "32", age: 35, height: "6'2\"", conf: "West", previousTeams: ["PHX", "IND", "CON"] },
  { id: 41, name: "Julie Allemand", team: "LAS", position: "G", number: "20", age: 28, height: "5'8\"", conf: "West", previousTeams: ["IND", "CHI"] },
  { id: 47, name: "Kelsey Plum", team: "LAS", position: "G", number: "10", age: 30, height: "5'8\"", conf: "West", previousTeams: ["LVA"] },
  { id: 56, name: "Mercedes Russell", team: "LAS", position: "C", number: "21", age: 29, height: "6'6\"", conf: "West", previousTeams: [] },
  { id: 64, name: "Odyssey Sims", team: "LAS", position: "G", number: "0", age: 32, height: "5'8\"", conf: "West", previousTeams: ["MIN", "ATL", "DAL"] },
  { id: 66, name: "Rae Burrell", team: "LAS", position: "G-F", number: "12", age: 24, height: "6'2\"", conf: "West", previousTeams: [] },
  { id: 69, name: "Rickea Jackson", team: "LAS", position: "F", number: "2", age: 23, height: "6'2\"", conf: "West", previousTeams: [] },
  { id: 72, name: "Sania Feagin", team: "LAS", position: "F", number: "1", age: 22, height: "6'3\"", conf: "West", previousTeams: [] },
  { id: 73, name: "Sarah Ashlee Barker", team: "LAS", position: "G", number: "13", age: 23, height: "6'0\"", conf: "West", previousTeams: [] },

  // LVA
  { id: 1, name: "A'ja Wilson", team: "LVA", position: "C-F", number: "22", age: 27, height: "6'4\"", conf: "West", previousTeams: [] },
  { id: 2, name: "Aaliyah Nye", team: "LVA", position: "G-F", number: "13", age: 22, height: "6'0\"", conf: "West", previousTeams: [] },
  { id: 18, name: "Chelsea Gray", team: "LVA", position: "G", number: "12", age: 32, height: "5'11\"", conf: "West", previousTeams: ["LAS", "CON"] },
  { id: 19, name: "Cheyenne Parker-Tyus", team: "LVA", position: "F", number: "24", age: 32, height: "6'4\"", conf: "West", previousTeams: ["CHI", "ATL"] },
  { id: 23, name: "Dana Evans", team: "LVA", position: "G", number: "11", age: 26, height: "5'6\"", conf: "West", previousTeams: ["CHI"] },
  { id: 37, name: "Jackie Young", team: "LVA", position: "G", number: "0", age: 27, height: "6'0\"", conf: "West", previousTeams: [] },
  { id: 39, name: "Jewell Loyd", team: "LVA", position: "G", number: "24", age: 29, height: "5'10\"", conf: "West", previousTeams: ["SEA"] },
  { id: 48, name: "Kiah Stokes", team: "LVA", position: "C", number: "41", age: 31, height: "6'3\"", conf: "West", previousTeams: ["NYL"] },
  { id: 49, name: "Kierstan Bell", team: "LVA", position: "F", number: "1", age: 24, height: "6'1\"", conf: "West", previousTeams: [] },
  { id: 55, name: "Megan Gustafson", team: "LVA", position: "C", number: "17", age: 28, height: "6'3\"", conf: "West", previousTeams: ["DAL", "PHX", "WAS"] },
  { id: 80, name: "Tiffany Mitchell", team: "SEA", position: "G", number: "3", age: 30, height: "5'9\"", conf: "West", previousTeams: ["IND", "MIN", "CON", "LVA"] },

  // MIN
  { id: 5, name: "Alanna Smith", team: "MIN", position: "F", number: "11", age: 27, height: "6'4\"", conf: "West", previousTeams: ["PHX", "IND"] },
  { id: 15, name: "Bridget Carleton", team: "MIN", position: "F", number: "6", age: 27, height: "6'1\"", conf: "West", previousTeams: ["CON", "ATL"] },
  { id: 20, name: "Courtney Williams", team: "MIN", position: "G", number: "10", age: 31, height: "5'8\"", conf: "West", previousTeams: ["ATL", "CON"] },
  { id: 28, name: "Diamond Miller", team: "MIN", position: "F", number: "1", age: 24, height: "6'3\"", conf: "West", previousTeams: [] },
  { id: 29, name: "Dorka Juhasz", team: "MIN", position: "F", number: "14", age: 23, height: "6'5\"", conf: "West", previousTeams: [] },
  { id: 45, name: "Kayla McBride", team: "MIN", position: "G", number: "21", age: 32, height: "5'11\"", conf: "West", previousTeams: ["LVA"] },
  { id: 59, name: "Napheesa Collier", team: "MIN", position: "F", number: "24", age: 28, height: "6'1\"", conf: "West", previousTeams: [] },
  { id: 61, name: "Natisha Hiedeman", team: "MIN", position: "G", number: "2", age: 26, height: "5'8\"", conf: "East", previousTeams: ["CON"] },
  { id: 91, name: "Maria Kliundikova", team: "MIN", position: "C", number: "77", age: 27, height: "6'4\"", conf: "West", previousTeams: ["LAS"] },
  { id: 92, name: "Anastasiia Kosu", team: "MIN", position: "F", number: "7", age: 20, height: "6'1\"", conf: "West", previousTeams: [] },
  { id: 93, name: "Alissa Pili", team: "LAS", position: "F", number: "35", age: 23, height: "6'2\"", conf: "West", previousTeams: ["MIN"] },
  { id: 95, name: "Jessica Shepard", team: "MIN", position: "F", number: "15", age: 28, height: "6'4\"", conf: "West", previousTeams: [] },

  // NYL
  { id: 13, name: "Breanna Stewart", team: "NYL", position: "F", number: "30", age: 31, height: "6'4\"", conf: "East", previousTeams: ["SEA"] },
  { id: 36, name: "Isabelle Harrison", team: "NYL", position: "F", number: "20", age: 32, height: "6'3\"", conf: "East", previousTeams: ["PHO", "LVA", "DAL", "CHI"] },
  { id: 40, name: "Jonquel Jones", team: "NYL", position: "C", number: "35", age: 31, height: "6'6\"", conf: "East", previousTeams: ["CON"] },
  { id: 71, name: "Sabrina Ionescu", team: "NYL", position: "G", number: "20", age: 28, height: "5'11\"", conf: "East", previousTeams: [] },
  { id: 141, name: "Emma Meesseman", team: "NYL", position: "F", number: "33", age: 32, height: "6'4\"", conf: "East", previousTeams: ["WAS", "CHI"] },
  { id: 143, name: "Rebekah Gardner", team: "NYL", position: "G", number: "35", age: 35, height: "6'1\"", conf: "East", previousTeams: ["CHI"] },
  { id: 144, name: "Nyara Sabally", team: "NYL", position: "C", number: "8", age: 25, height: "6'5\"", conf: "East", previousTeams: [] },
  { id: 145, name: "Natasha Cloud", team: "NYL", position: "G", number: "15", age: 33, height: "5'10\"", conf: "East", previousTeams: ["WAS", "PHO"] },
  { id: 146, name: "Leonie Fiebich", team: "NYL", position: "F", number: "13", age: 25, height: "6'4\"", conf: "East", previousTeams: [] },
  { id: 147, name: "Kennedy Burke", team: "NYL", position: "G-F", number: "22", age: 28, height: "6'1\"", conf: "East", previousTeams: ["IND", "SEA", "WAS"] },
  { id: 148, name: "Marine Johannès", team: "NYL", position: "G", number: "23", age: 30, height: "5'10\"", conf: "East", previousTeams: [] },

  // PHX
  { id: 8, name: "Alyssa Thomas", team: "PHX", position: "F", number: "25", age: 31, height: "6'2\"", conf: "West", previousTeams: ["CON"] },
  { id: 43, name: "Kahleah Copper", team: "PHX", position: "G-F", number: "2", age: 28, height: "6'1\"", conf: "West", previousTeams: ["CHI"] },
  { id: 74, name: "Satou Sabally", team: "PHX", position: "F", number: "0", age: 26, height: "6'4\"", conf: "West", previousTeams: ["DAL"] },
  { id: 2, name: "Lexi Held", team: "PHX", position: "G", number: "", age: 26, height: "5'10\"", conf: "West", previousTeams: [] },
  { id: 4, name: "Natasha Mack", team: "PHX", position: "F-C", number: "8", age: 28, height: "6'3\"", conf: "West", previousTeams: ["CHI", "MIN",] },
  { id: 5, name: "Monique Akoa Makani", team: "PHX", position: "G", number: "", age: 0, height: "", conf: "West", previousTeams: [] },
  { id: 6, name: "Kitija Laksa", team: "PHX", position: "G", number: "3", age: 29, height: "6'0\"", conf: "West", previousTeams: [] },
  
  { id: 9, name: "Kalani Brown", team: "PHX", position: "C", number: "21", age: 28, height: "6'7\"", conf: "West", previousTeams: ["LAS", "ATL", "DAL"] },
  { id: 10, name: "Kathryn Westbeld", team: "PHX", position: "F", number: "", age: 29, height: "6'2\"", conf: "West", previousTeams: [] },
  { id: 12, name: "Sami Whitcomb", team: "PHX", position: "G", number: "3", age: 37, height: "5'10\"", conf: "West", previousTeams: ["SEA", "NYL"] },
  { id: 26, name: "DeWanna Bonner", team: "PHX", position: "G-F", number: "24", age: 38, height: "6'4\"", conf: "West", previousTeams: ["PHO", "CON", "IND"] },

  // SEA
  { id: 7, name:  "Alysha Clark", team: "SEA", position: "F", number: "7", age: 37, height: "5'11\"", conf: "West", previousTeams: ["WAS"] },
  { id: 34, name: "Gabby Williams", team: "SEA", position: "F", number: "5", age: 28, height: "5'11\"", conf: "West", previousTeams: ["CHI"] },
  { id: 62, name: "Nika Muhl", team: "SEA", position: "G", number: "1", age: 22, height: "5'9\"", conf: "West", previousTeams: [] },
  { id: 63, name: "Nneka Ogwumike", team: "SEA", position: "F", number: "3", age: 34, height: "6'2\"", conf: "West", previousTeams: ["LAS"] },
  { id: 76, name: "Skylar Diggins", team: "SEA", position: "G", number: "4", age: 33, height: "5'9\"", conf: "West", previousTeams: ["PHX", "DAL"] },
  { id: 11, name: "Katie Lou Samuelson", team: "SEA", position: "F", number: "44", age: 30, height: "6'0\"", conf: "West", previousTeams: ["LAS", "DAL", "PHO", "WAS", "MIN"] },
  { id: 9, name:  "Li Yueru", team: "SEA", position: "C", number: "28", age: 26, height: "6'7\"", conf: "West", previousTeams: ["CHI", "LAS"] },
  { id: 8, name:  "Erica Wheeler", team: "SEA", position: "G", number: "17", age: 34, height: "5'7\"", conf: "West", previousTeams: ["ATL", "NYL", "IND", "LAS"] },
  { id: 7, name:  "Dominique Malonga", team: "SEA", position: "C", number: "14", age: 20, height: "6'6\"", conf: "West", previousTeams: [] },
  { id: 6, name:  "Ezi Magbegor", team: "SEA", position: "F-C", number: "13", age: 26, height: "6'4\"", conf: "West", previousTeams: [] },
  { id: 5, name:  "Lexie Brown", team: "SEA", position: "G", number: "8", age: 30, height: "6'0\"", conf: "West", previousTeams: ["CON", "MIN", "CHI", "LAS"] },
  { id: 4, name:  "Zia Cooke", team: "SEA", position: "G", number: "1", age: 24, height: "5'9\"", conf: "West", previousTeams: ["LAS"] },


  // WAS
  { id: 50, name: "Kiki Iriafen", team: "WAS", position: "F", number: "44", age: 22, height: "6'3\"", conf: "East", previousTeams: [] },
  { id: 75, name: "Shakira Austin", team: "WAS", position: "F-C", number: "0", age: 25, height: "6'5\"", conf: "East", previousTeams: [] },
  { id: 81, name: "Georgia Amoore", team: "WAS", position: "G", number: "8", age: 24, height: "5'6\"", conf: "East", previousTeams: [] },
  { id: 82, name: "Sonia Citron", team: "WAS", position: "G", number: "22", age: 21, height: "6'1\"", conf: "East", previousTeams: [] },
  { id: 83, name: "Stefanie Dolson", team: "WAS", position: "C", number: "31", age: 33, height: "6'5\"", conf: "East", previousTeams: [] },
  
  { id: 85, name: "Emily Engstler", team: "WAS", position: "F", number: "21", age: 25, height: "6'1\"", conf: "East", previousTeams: [] },
  { id: 86, name: "Sika Kone", team: "WAS", position: "F", number: "3", age: 22, height: "6'3\"", conf: "East", previousTeams: [] },
  { id: 87, name: "Jade Melbourne", team: "WAS", position: "G", number: "5", age: 22, height: "5'10\"", conf: "East", previousTeams: [] },
  { id: 88, name: "Lucy Olsen", team: "WAS", position: "G", number: "33", age: 21, height: "5'10\"", conf: "East", previousTeams: [] },
  { id: 89, name: "Sug Sutton", team: "WAS", position: "G", number: "1", age: 26, height: "5'8\"", conf: "East", previousTeams: [] },
  { id: 90, name: "Brittney Sykes", team: "WAS", position: "G", number: "20", age: 31, height: "5'9\"", conf: "East", previousTeams: [] },
  { id: 97, name: "Jacy Sheldon", team: "WAS", position: "G", number: "4", age: 25, height: "5'10\"", conf: "East", previousTeams: ["DAL", "CON"] },
];

export default players;